name: Test
on: [ push, pull_request, workflow_dispatch ]

jobs:
    test:
        name: Run tests
        runs-on: macOS-latest
        steps:
            -   name: Checkout sources
                uses: actions/checkout@v6

            -   name: Setup Java
                uses: actions/setup-java@v5
                with:
                    distribution: "graalvm"
                    java-version: 21

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v5

            -   name: Run tests
                run: ./gradlew cleanAllTests allTests --stacktrace

            -   name: Upload test report
                if: success() || failure()
                uses: actions/upload-artifact@v7
                with:
                    name: Test report
                    path: core/build/reports/tests/allTests/
